"""initial migration

Revision ID: 22b5d87f2012
Revises: 
Create Date: 2026-07-08 04:58:32.762309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '22b5d87f2012'
down_revision: Union[str, Sequence[str], None] = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'max_att',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blocked_ip_addresses', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('contact_messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('news_letters', 'last_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news_letters', 'last_open',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('contact_messages', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blocked_ip_addresses', 'phone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('admins', 'max_att',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###