"""a

Revision ID: 607df7182526
Revises: 6b551ce038ee
Create Date: 2026-07-28 14:46:26.437968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '607df7182526'
down_revision: Union[str, Sequence[str], None] = '6b551ce038ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'vendors', ['vendor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'vendor_id')
    op.drop_column('orders', 'product_id')
    op.drop_column('orders', 'user_phone')
    # ### end Alembic commands ###
