"""a

Revision ID: 6a903be8c2f3
Revises: 0995d360ac7b
Create Date: 2026-07-27 13:53:54.304736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a903be8c2f3'
down_revision: Union[str, Sequence[str], None] = '0995d360ac7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('otps', sa.Column('email', sa.String(), nullable=False))
    op.add_column('otps', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'expires_at')
    op.drop_column('otps', 'email')
    op.drop_column('otps', 'is_used')
    # ### end Alembic commands ###
