"""a

Revision ID: 6b551ce038ee
Revises: 42e056dc8d07
Create Date: 2026-07-28 10:57:43.797436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b551ce038ee'
down_revision: Union[str, Sequence[str], None] = '42e056dc8d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('is_vendor', sa.Boolean(), nullable=True))
    op.add_column('vendors', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'is_deleted')
    op.drop_column('vendors', 'is_vendor')
    # ### end Alembic commands ###
