"""a

Revision ID: c78c4542e4d5
Revises: d69bb9c8a8f8
Create Date: 2026-07-29 04:43:07.202456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c78c4542e4d5'
down_revision: Union[str, Sequence[str], None] = 'd69bb9c8a8f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('amount', sa.Float(), nullable=False))
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('payments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('subscriptions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.add_column('subscriptions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint(op.f('subscriptions_vendor_id_fkey'), 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'vendors', ['user_id'], ['id'])
    op.create_foreign_key(None, 'subscriptions', 'payments', ['payment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscriptions', 'vendor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_vendor_id_fkey'), 'subscriptions', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('subscriptions', 'expires_at')
    op.drop_column('subscriptions', 'payment_id')
    op.drop_column('subscriptions', 'user_id')
    op.drop_column('payments', 'updated_at')
    op.drop_column('payments', 'created_at')
    op.drop_column('payments', 'amount')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
