"""a

Revision ID: d69bb9c8a8f8
Revises: fea0ad8a73b4
Create Date: 2026-07-28 17:36:27.175215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69bb9c8a8f8'
down_revision: Union[str, Sequence[str], None] = 'fea0ad8a73b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_name')
    # ### end Alembic commands ###
